# Generated by Django 4.1.1 on 2022-09-20 20:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(80)]),
        ),
    ]
