# Generated by Django 4.1.1 on 2022-09-20 22:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(80), django.core.validators.RegexValidator('[^0-9a-zA-Z]', code='no_blanks', message='Enter value')]),
        ),
    ]
